name: A pull-request pipeline

on:
  pull_request_target:

jobs:
  lint:
    name: Running vue-cli-serve lint via yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.number }}/merge'
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: yarn set version berry
      - run: yarn install
      - name: Run linter with the --no-fix option
        run: yarn lint --no-fix --max-warnings=0

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out the target commit (${{ github.sha }})
      uses: actions/checkout@v2
      with:
        ref: 'refs/pull/${{ github.event.number }}/merge'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: '14'
    - run: npm install -g yarn
    - run: yarn set version berry
    - run: yarn install
    - name: Build packages
      run: yarn build
